Add back increasing ring feature [3/3]
 squashed with:

   Telecomm: İncreasing ring feature: add missing attribute

   packages/services/Telecomm/src/com/android/server/telecom/Ringer.java:400:
   error: method play in class AsyncRingtonePlayer cannot be applied to given types;
                hapticsFuture = mRingtonePlayer.play(mRingtoneFactory, foregroundCall,
                                               ^
     required: RingtoneFactory,Call,Configuration,boolean,boolean
     found: RingtoneFactory,Call,Configuration,boolean
     reason: actual and formal argument lists differ in length
   Change-Id: I96c33e711929655a3b3be35b93f2ba292ae59201

Change-Id: I1d5173fb8134400e5fa72c19181f34e1a5ec4e0d